FROM oven/bun:1.2-slim

WORKDIR /app

COPY package.json bun.lock ./
COPY prisma ./prisma/

RUN bun install --frozen-lockfile

RUN bunx prisma generate

COPY . .

EXPOSE 4001


CMD ["bun", "run", "src/index.ts"]